import json
import yaml
import joblib
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler

PROJ_ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = PROJ_ROOT / "config.yaml"

with open(CONFIG_PATH, "r") as f:
    config = yaml.safe_load(f)

raw_path = PROJ_ROOT / config["data"]["raw_path"]
processed_dir = PROJ_ROOT / config["data"]["processed_dir"]
version = config["data"]["current_version"]

processed_dir.mkdir(exist_ok = True)
df = pd.read_csv(raw_path)
df = df.dropna()
# Add code to preprocess the data (e.g., handle missing values, encode categorical variables, scale features)
drop_cols = config["features"]["drop_columns"]
target_col = config["features"]["target"]
cat_cols = config["features"]["categorical"]
scale_numeric = config["features"]["scale_numeric"]

df = df.drop(columns = drop_cols, errors = "ignore")
df = pd.get_dummies(df, columns = cat_cols, drop_first = True)
X = df.drop(columns = target_col)
y = df[target_col]

train_size = config["data"]["train_size"]
X_train = X.iloc[:train_size].copy()
X_test = X.iloc[train_size:].copy()
y_train = y.iloc[:train_size].copy()
y_test = y.iloc[train_size:].copy()


"""
if scale_numeric:
    scaler = StandardScaler()
    numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
    numeric_cols_path = processed_dir / f"{version}_numeric_cols.json"
    with open(numeric_cols_path, "w") as f:
        json.dump(numeric_cols, f)
    X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
    X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])
"""
#scaler_path = processed_dir / f"{version}_scaler.joblib"
#joblib.dump(scaler, scaler_path)
train_df = pd.concat([X_train, y_train], axis = 1)
test_df = pd.concat([X_test, y_test], axis = 1)

train_path = processed_dir / f"{version}_train.csv"
test_path = processed_dir / f"{version}_test.csv"

if train_path.exists() or test_path.exists():
    raise FileExistsError(
        f"""Processed files already exist for version {version}.
        Please update the version"""
    )
train_df.to_csv(train_path, index = False)
test_df.to_csv(test_path, index = False)

manifest_path = processed_dir / "manifest.txt"
with open(manifest_path, "a") as f:
    f.write(
        f"""
Version: {version}
Timestamp: {pd.Timestamp.now()}
Generated by: src/data_prep.py
Source: {raw_path}
train_rows: {train_size}
test_rows: {len(test_df)}
Added file(s): {train_path.name}, {test_path.name}
Features: {list(X_train.columns)}\n
        """
    )